### ISSUE TITLE
Avogadro2 Not Able to Parse Written PDB Files

### ISSUE THREAD

**Issue by Dfilono** [Dfilono/Molecule-Builder#3]
Avogadro2 is struggling to parse either the Z coordinate or the Residue Sequence Number and so it is not showing the PDB structure.

**Comment by ghutchis** [comment]
Can you post an example file? I can definitely find the problem.

For example, take a look:
https://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM

PDB expects certain columns based on character counts.

**Comment by Dfilono** [comment]
Sure! I've attached a file. I think I know the issue then, if I am generating unique names and IDs for atoms, I think they eventually just get too long? I'm not sure how to combat this at the moment. I'll have to think about it. Let me know if you find a different issue/solution!
[WaterOut.txt](https://github.com/Dfilono/Molecule-Builder/files/12875872/WaterOut.txt)

**Comment by ghutchis** [comment]
Yeah, you need to look at the specification.
- First off, if this isn't an amino acid or nucleic acid, you should use "HETATM" as the record specifier.
- Don't just create residue names. Since these are water, you should use "HOH" as the residue field.
- Your fields are shifting because you're not using a fixed number of characters.

See, for example: https://stackoverflow.com/a/10837046/131896

Here's the PDB write for Open Babel:
https://github.com/openbabel/openbabel/blob/e7aa0942f6c7733950dcf49e3c8e7f1b56feeea5/src/formats/pdbformat.cpp#L748C11-L748C11

**Comment by chriswilmer** [comment]
I think each atom label might need to be strictly two characters.
